apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-${nodenumber}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: es-${nodenumber}
        escluster: es
    spec:
      containers:
        - name: es-${nodenumber}
          image: "eventstore/eventstore"
          env: 
            - name: EVENTSTORE_INT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EVENTSTORE_EXT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EVENTSTORE_INT_TCP_PORT
              value: "3111"
            - name: EVENTSTORE_EXT_TCP_PORT
              value: "3112"
            - name: EVENTSTORE_INT_HTTP_PORT
              value: "4111"
            - name: EVENTSTORE_EXT_HTTP_PORT
              value: "4112"
            - name: EVENTSTORE_CLUSTER_SIZE
              value: "${nodecount}"
            - name: EVENTSTORE_CLUSTER_DNS
              value: "es-pd"
            - name: EVENTSTORE_CLUSTER_GOSSIP_PORT
              value: "4111"
            - name: EVENTSTORE_GOSSIP_ALLOWED_DIFFERENCE_MS
              value: "600000"
            - name: EVENTSTORE_INT_HTTP_PREFIXES
              value: "http://*:4111/"
            - name: EVENTSTORE_EXT_HTTP_PREFIXES
              value: "http://*:4112/"
            - name: EVENTSTORE_DB
              value: "/usr/data/eventstore/data"
            - name: EVENTSTORE_LOG
              value: "/usr/data/eventstore/log"
          ports:
            - containerPort: 3111
            - containerPort: 3112
            - containerPort: 4111
            - containerPort: 4112
          volumeMounts:
            - mountPath: "/usr/data/eventstore"
              name: espd
      volumes:
        - name: espd
          azureFile:
            secretName: azure-secret
            shareName: esdisk-${nodenumber}
            readOnly: false
